services:
  client:
    image: client
    build:
      context: client
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    command: npm run dev
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules

  server:
    image: server
    build:
      context: server
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports: 
      - 5000:5000
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev
