version: '3.4'

services:
  client:
    image: client
    build:
      context: client
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3001:3000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
  
  server:
    image: server
    build:
      context: server
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV: development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    ports:
      -5001:5000
      -9300:9300
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
